### ISSUE TITLE
Does it support macOS?

### ISSUE THREAD

**Issue by simpzan** [krzysztofzablocki/Traits#5]

**Comment by krzysztofzablocki** [comment]
The bundled traits here target iOS, but the tool / idea would work fine on mac, we'd just need to filter out specific Traits in the podspec, its only based on NSObject and objc runtime not UIKit

**Comment by simpzan** [comment]
That is so great! 
The most attractive feature of React Native is the great developer experience, thanks to the hot reloading feature. 
Now there's hot reloading solution for apple platform, the react native is not so attractive if I only target apple platform. :)
