### ISSUE TITLE
Can we make it work with UIAppearance?

### ISSUE THREAD

**Issue by antonselyanin** [krzysztofzablocki/Traits#6]
AFAIK, UIAppearance uses proxy objects, so we can't just set trait specs for them.

Here is what I had to do to make it work with UIAppearance.

1. Disable `restrictedTypes` check (can't add private `_UIAppearance` type to the list)
2. Use `unsafeBitCast` instead of force cast on target objects (force cast traps while trying to cast `_UIAppearance` to something else)
3. Re-add root `UIView`s for all `UIWindow`s after traits are reloaded (so that the changes in UIAppearance take effect).
Maybe there is a better way to accomplish it.

The first two hacks are very dirty, but we could try to wrap them in an abstration.
We could introduce something like 'TypeCastingStrategy' and use different implementations for normal objects and UIAppearance proxies. 

The hack with re-adding UIViews seems simple and working, but there could be some downsides I'm not aware of.

What do you think about this? Is support of UIAppearance worth hacking?
I could try to make a prototype :)

**Comment by krzysztofzablocki** [comment]
I think that `UIApperance` is nice, but I avoided using it here because I wanted to have something more generic and also because it wouldn't be easy to do specific elements.

for `UIApperance` my friend @robertwijas made https://github.com/robertwijas/UISS

**Comment by antonselyanin** [comment]
Well, I mostly use `UIAppearance` for styling `UINavigationBar`. How can I do the same using Traits?

Lets say, I have `BarTintColor` and `BarTitleTextAttributes` traits and I can use them for styling `UINavigationBar`. I could just set `traitSpec` for every nav bar in the app (like, whenever I create a `UINavigationController`).

I guess this is OK. Or is there a better way? :)

**Comment by krzysztofzablocki** [comment]
you could make fake object that serves as target and uses apperance if you really wanted to given how flexible the tool is. What you described is more natural way of using the tool :)

**Comment by antonselyanin** [comment]
Wow, this idea with fake object is way better than `unsafeBitCast`!
Thanks!
